<div class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Keep the catalog tidy and ready to sell.</p></div><button class="btn btn-primary" type="button" wire:click="create"><x-icon name="plus" size="17" /> New product</button></div>

    @if($showForm)
        <section class="surface p-5 sm:p-6">
            <div class="mb-6 flex items-start justify-between gap-4"><div><p class="eyebrow">{{ $editingId ? 'Edit catalog item' : 'New catalog item' }}</p><h2 class="mt-1 text-xl font-bold text-slate-950">{{ $editingId ? 'Update product' : 'Add a product' }}</h2></div><button class="btn btn-secondary" type="button" wire:click="$set('showForm', false)"><x-icon name="x" size="16" /> Close</button></div>
            <form class="grid gap-5 md:grid-cols-2" wire:submit="save">
                <div><label class="field-label" for="product-name">Name</label><input id="product-name" class="field-control" wire:model="name" type="text">@error('name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="field-label" for="product-sku">SKU</label><input id="product-sku" class="field-control" wire:model="sku" type="text">@error('sku')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="field-label" for="product-slug">Slug <span class="font-normal text-slate-400">(optional)</span></label><input id="product-slug" class="field-control" wire:model="slug" type="text">@error('slug')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="field-label" for="product-category">Category</label><select id="product-category" class="field-control" wire:model="categoryId"><option value="">Choose a category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>@error('categoryId')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="field-label" for="product-price">Price</label><input id="product-price" class="field-control" wire:model="price" type="number" step="0.01" min="0">@error('price')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="field-label" for="product-stock">Stock quantity</label><input id="product-stock" class="field-control" wire:model="stockQuantity" type="number" min="0">@error('stockQuantity')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div class="md:col-span-2"><label class="field-label" for="product-description">Description</label><textarea id="product-description" class="field-control min-h-28" wire:model="description"></textarea>@error('description')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div class="flex flex-wrap gap-5 md:col-span-2"><label class="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><input class="size-4 rounded border-slate-300 text-orange-600 focus:ring-orange-500" wire:model="isPublished" type="checkbox"> Published</label><label class="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><input class="size-4 rounded border-slate-300 text-orange-600 focus:ring-orange-500" wire:model="isFeatured" type="checkbox"> Featured</label></div>
                <div class="flex justify-end gap-3 md:col-span-2"><button class="btn btn-secondary" type="button" wire:click="resetForm">Reset</button><button class="btn btn-primary" type="submit">Save product</button></div>
            </form>
        </section>
    @endif

    <section class="surface overflow-hidden">
        <div class="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-[1fr_180px_160px]"><label class="relative"><span class="sr-only">Search products</span><x-icon name="search" size="17" class="absolute left-3 top-3 text-slate-400" /><input class="field-control pl-10" wire:model.live.debounce.300ms="search" placeholder="Search name or SKU" type="search"></label><select class="field-control" wire:model.live="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><select class="field-control" wire:model.live="status"><option value="">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select></div>
        @if($errors->has('product'))<div class="border-b border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first('product') }}</div>@endif
        <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3 font-semibold">Product</th><th class="px-5 py-3 font-semibold">Category</th><th class="px-5 py-3 font-semibold">Price</th><th class="px-5 py-3 font-semibold">Stock</th><th class="px-5 py-3 font-semibold">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($products as $product)<tr wire:key="product-{{ $product->id }}" class="hover:bg-slate-50"><td class="px-5 py-4"><div class="flex items-center gap-3"><x-product-placeholder :product="$product" size="sm" /><div><p class="font-semibold text-slate-900">{{ $product->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $product->sku }}</p></div></div></td><td class="px-5 py-4 text-slate-600">{{ $product->category?->name ?? 'Uncategorized' }}</td><td class="px-5 py-4 font-semibold text-slate-900">${{ number_format($product->price, 2) }}</td><td class="px-5 py-4"><span class="font-semibold {{ $product->stock_quantity <= 5 ? 'text-red-600' : 'text-slate-700' }}">{{ $product->stock_quantity }}</span></td><td class="px-5 py-4"><x-status-badge :status="$product->is_published ? 'approved' : 'draft'" /></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><button class="btn btn-secondary px-3 py-2" type="button" wire:click="edit({{ $product->id }})"><x-icon name="edit" size="15" /> Edit</button><button class="rounded-xl p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" type="button" wire:click="delete({{ $product->id }})" wire:confirm="Archive this product?"><x-icon name="trash" size="16" /></button></div></td></tr>@empty<tr><td class="px-5 py-12" colspan="6"><x-empty-state title="No products found" description="Try another search or add your first catalog item." /></td></tr>@endforelse
        </tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $products->links() }}</div>
    </section>
</div>
