<div>
    <a href="{{ route('orders') }}" class="mb-7 inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-orange-600"><x-icon name="arrow-left" size="16" /> Back to orders</a>
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Order details</p><h1 class="mt-2 text-4xl font-bold tracking-tight text-slate-950">#{{ $order->order_number }}</h1><p class="mt-2 text-sm text-slate-500">Placed {{ $order->created_at->format('M d, Y · H:i') }}</p></div><x-status-badge :status="$order->status" /></div>
    @if(session('success'))<div class="mt-6"><x-alert type="success" :message="session('success')" /></div>@endif
    @error('order')<div class="mt-6"><x-alert type="error" :message="$message" /></div>@enderror
    <div class="mt-8 grid gap-8 lg:grid-cols-[1fr_330px] lg:items-start">
        <div class="space-y-6">
            <section class="surface overflow-hidden"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-semibold text-slate-950">Items in this order</h2></div><div class="divide-y divide-slate-100">@foreach($order->orderItems as $item)<div class="flex gap-4 p-5"><div class="size-16 shrink-0 overflow-hidden rounded-xl bg-orange-50">@if($item->product?->image)<img src="{{ $item->product->image }}" alt="{{ $item->product_name }}" class="h-full w-full object-cover">@else<x-product-placeholder :product="$item->product ?? (object)['initials' => 'LS']" size="small" />@endif</div><div class="min-w-0 flex-1"><p class="font-semibold text-slate-950">{{ $item->product_name ?? $item->product?->name }}</p><p class="mt-1 text-sm text-slate-500">Qty {{ $item->quantity }} · ${{ number_format($item->price, 2) }} each</p></div><p class="font-semibold text-slate-950">${{ number_format($item->price * $item->quantity, 2) }}</p></div>@endforeach</div><div class="flex justify-between border-t border-slate-100 px-5 py-5 text-lg font-bold text-slate-950"><span>Total</span><span>${{ number_format($order->total_amount, 2) }}</span></div></section>
            @if($order->isFulfilled())<section class="surface p-5"><p class="eyebrow">Share the useful details</p><h2 class="mt-2 text-xl font-bold text-slate-950">Leave a review</h2><p class="mt-2 text-sm text-slate-500">Reviews are held for a quick moderation pass before they appear publicly.</p>@if($reviewProductId)<div class="mt-5 rounded-xl bg-slate-50 p-4"><label class="field-label">Rating</label><select wire:model="reviewRating" class="field-control"><option value="5">5 — Excellent</option><option value="4">4 — Great</option><option value="3">3 — Good</option><option value="2">2 — Fair</option><option value="1">1 — Poor</option></select><input wire:model="reviewTitle" class="field-control mt-3" placeholder="Review title (optional)"><textarea wire:model="reviewBody" rows="3" class="field-control mt-3" placeholder="What did you think?"></textarea>@error('reviewBody')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror<div class="mt-3 flex gap-2"><button wire:click="saveReview" class="btn btn-primary">Submit review</button><button wire:click="$set('reviewProductId', null)" class="btn btn-secondary">Cancel</button></div></div>@else<div class="mt-5 flex flex-wrap gap-2">@foreach($order->orderItems as $item)@if(!$order->reviews->contains('product_id', $item->product_id))<button wire:click="startReview({{ $item->product_id }})" class="btn btn-secondary">Review {{ $item->product_name ?? $item->product?->name }}</button>@endif @endforeach</div>@endif</section>@endif
        </div>
        <aside class="space-y-6"><section class="surface p-5"><h2 class="font-semibold text-slate-950">Order timeline</h2><div class="mt-5 space-y-5">@foreach($order->statusHistories->sortBy('created_at') as $history)<div class="relative flex gap-3"><span class="mt-1 flex size-5 shrink-0 items-center justify-center rounded-full bg-orange-100 text-orange-600"><x-icon name="check" size="12" /></span><div><p class="text-sm font-semibold capitalize text-slate-900">{{ str_replace('_', ' ', $history->to_status) }}</p><p class="mt-0.5 text-xs text-slate-500">{{ $history->note }} · {{ $history->created_at->format('M d, H:i') }}</p></div></div>@endforeach</div></section><section class="surface p-5"><h2 class="font-semibold text-slate-950">Delivery details</h2><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $order->shipping_address }}</p><p class="mt-4 text-xs text-slate-500">{{ $order->customer_name }} · {{ $order->customer_phone }}</p></section>@if($order->canBeCancelled())<button wire:click="cancel" wire:confirm="Cancel this order and return its items to stock?" class="btn btn-secondary w-full text-red-600 hover:border-red-200 hover:bg-red-50">Cancel order</button>@endif</aside>
    </div>
</div>
