import router from '@adonisjs/core/services/router'
import { middleware } from '#start/kernel'
import { authThrottle, checkoutThrottle } from '#start/limiter'

const Wishlist = () => import('#controllers/account/wishlist_controller')
const Reviews = () => import('#controllers/account/reviews_controller')
const CheckoutOptions = () => import('#controllers/storefront/checkout_options_controller')
const Payments = () => import('#controllers/account/payments_controller')
const Checkout = () => import('#controllers/storefront/checkout_controller')
const Orders = () => import('#controllers/account/orders_controller')
const Addresses = () => import('#controllers/account/addresses_controller')
const Cart = () => import('#controllers/storefront/cart_controller')
const Home = () => import('#controllers/storefront/home_controller')
const Locale = () => import('#controllers/storefront/locale_controller')
const Seo = () => import('#controllers/storefront/seo_controller')
const Health = () => import('#controllers/health_controller')
const Session = () => import('#controllers/account/session_controller')
const Registration = () => import('#controllers/account/registration_controller')
const Profile = () => import('#controllers/account/profile_controller')
const Catalog = () => import('#controllers/storefront/catalog_controller')
const Products = () => import('#controllers/admin/catalog_products_controller')
const Categories = () => import('#controllers/admin/catalog_categories_controller')
const Inventory = () => import('#controllers/admin/inventory_controller')
const Dashboard = () => import('#controllers/admin/dashboard_controller')
const AdminOrders = () => import('#controllers/admin/orders_controller')
const Customers = () => import('#controllers/admin/customers_controller')
const ModuleConfiguration = () => import('#controllers/admin/module_configuration_controller')
const Modules = () => import('#controllers/admin/modules_controller')
const Settings = () => import('#controllers/admin/settings_controller')

router.get('/', [Home, 'show']).as('home')
router.post('/locale', [Locale, 'update']).as('locale.update')
router.get('/products', [Catalog, 'index']).as('catalog')
router.get('/products/:slug', [Catalog, 'show']).as('product')
router.get('/cart', [Cart, 'show']).as('cart')
router.post('/cart/items', [Cart, 'add']).as('cart.add')
router.patch('/cart/items/:id', [Cart, 'update']).as('cart.update')
router.delete('/cart/items/:id', [Cart, 'remove']).as('cart.remove')
router.delete('/cart', [Cart, 'clear']).as('cart.clear')
router.get('/checkout', [Checkout, 'show'])
router.post('/checkout', [Checkout, 'store']).use(checkoutThrottle)
router.post('/checkout/options', [CheckoutOptions, 'update']).use(checkoutThrottle)
router.post('/orders/:id/payment/simulate', [Payments, 'simulate'])
router.get('/orders/:id', [Orders, 'show'])
router.post('/orders/:id/cancel', [Orders, 'cancel'])
router.get('/robots.txt', [Seo, 'robots'])
router.get('/sitemap.xml', [Seo, 'index'])
router.get('/sitemap/pages.xml', [Seo, 'pages'])
router.get('/sitemap/products/:page', [Seo, 'products'])
router.get('/health', [Health, 'live']).as('health')
router.get('/health/ready', [Health, 'ready']).as('health.ready')

router
  .group(() => {
    router.get('/login', [Session, 'show']).as('login')
    router.post('/login', [Session, 'store']).use(authThrottle)
    router.get('/register', [Registration, 'show']).as('register')
    router.post('/register', [Registration, 'store']).use(authThrottle)
  })
  .use(middleware.guest())

router
  .group(() => {
    router.post('/logout', [Session, 'destroy']).as('logout')
    router.get('/account/wishlist', [Wishlist, 'index'])
    router.post('/account/wishlist', [Wishlist, 'update'])
    router.delete('/account/wishlist/:id', [Wishlist, 'destroy'])
    router.post('/account/reviews', [Reviews, 'store'])
    router.get('/account/orders', [Orders, 'index'])
    router.get('/account/addresses', [Addresses, 'index'])
    router.post('/account/addresses', [Addresses, 'store'])
    router.put('/account/addresses/:id', [Addresses, 'update'])
    router.delete('/account/addresses/:id', [Addresses, 'destroy'])
    router.get('/account', [Profile, 'show']).as('account')
    router.patch('/account', [Profile, 'update'])
    router.get('/admin/inventory', [Inventory, 'index'])
    router.get('/admin/inventory/:id', [Inventory, 'show'])
    router.post('/admin/inventory/:id/adjust', [Inventory, 'adjust'])
    router.get('/admin/products', [Products, 'index'])
    router.get('/admin/products/create', [Products, 'create'])
    router.post('/admin/products', [Products, 'store'])
    router.get('/admin/products/:id/edit', [Products, 'edit'])
    router.put('/admin/products/:id', [Products, 'update'])
    router.get('/admin/categories', [Categories, 'index'])
    router.post('/admin/categories', [Categories, 'store'])
    router.put('/admin/categories/:id', [Categories, 'update'])
    router.get('/admin/orders', [AdminOrders, 'index'])
    router.get('/admin/orders/:id', [AdminOrders, 'show'])
    router.post('/admin/orders/:id/payment', [Payments, 'collect'])
    router.patch('/admin/orders/:id', [AdminOrders, 'update'])
    router.get('/admin/customers', [Customers, 'index'])
    router.get('/admin/customers/:id', [Customers, 'show'])
    router.patch('/admin/customers/:id', [Customers, 'update'])
    router.get('/admin/module-configuration', [ModuleConfiguration, 'index'])
    router.post('/admin/module-configuration/shipping', [ModuleConfiguration, 'shipping'])
    router.post('/admin/module-configuration/coupons', [ModuleConfiguration, 'coupon'])
    router.get('/admin/modules', [Modules, 'index'])
    router.put('/admin/modules', [Modules, 'update'])
    router.get('/admin', [Dashboard, 'index']).as('admin')
    router.get('/admin/settings', [Settings, 'edit']).as('admin.settings')
    router.put('/admin/settings', [Settings, 'update'])
  })
  .use(middleware.auth())
