<div>
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Almost there</p><h1 class="mt-2 text-4xl font-bold tracking-tight text-slate-950">Checkout</h1><p class="mt-3 text-slate-500">A simple, secure checkout for your LaraStore order.</p></div><a href="{{ route('cart.view') }}" class="link">Back to cart</a></div>
    @error('cart')<div class="mt-6"><x-alert type="error" :message="$message" /></div>@enderror
    <form wire:submit="placeOrder" class="mt-8 grid gap-8 lg:grid-cols-[1fr_360px] lg:items-start">
        <div class="space-y-6">
            <section class="surface p-6 sm:p-8"><div class="flex items-center gap-3"><span class="flex size-8 items-center justify-center rounded-full bg-orange-100 text-sm font-bold text-orange-700">1</span><div><h2 class="font-semibold text-slate-950">Contact details</h2><p class="text-sm text-slate-500">Where should we send your order updates?</p></div></div><div class="mt-6 grid gap-5 sm:grid-cols-2"><div><label class="field-label" for="checkout-name">Full name</label><input id="checkout-name" wire:model="name" class="field-control" />@error('name')<p class="mt-1.5 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="field-label" for="checkout-email">Email</label><input id="checkout-email" type="email" wire:model="email" class="field-control" />@error('email')<p class="mt-1.5 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="field-label" for="checkout-phone">Phone</label><input id="checkout-phone" wire:model="phone" class="field-control" placeholder="09 0000 0000" />@error('phone')<p class="mt-1.5 text-sm text-red-600">{{ $message }}</p>@enderror</div></div></section>
            <section class="surface p-6 sm:p-8"><div class="flex items-center gap-3"><span class="flex size-8 items-center justify-center rounded-full bg-orange-100 text-sm font-bold text-orange-700">2</span><div><h2 class="font-semibold text-slate-950">Delivery address</h2><p class="text-sm text-slate-500">We currently deliver within the practice project universe.</p></div></div><div class="mt-6"><label class="field-label" for="shipping-address">Shipping address</label><textarea id="shipping-address" wire:model.live="shippingAddress" rows="4" class="field-control" placeholder="Street, district, city"></textarea>@error('shippingAddress')<p class="mt-1.5 text-sm text-red-600">{{ $message }}</p>@enderror</div><label class="mt-5 flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" wire:model.live="sameBilling" class="size-4 rounded border-slate-300 text-orange-600 focus:ring-orange-500"> Billing address is the same</label>@unless($sameBilling)<div class="mt-5"><label class="field-label" for="billing-address">Billing address</label><textarea id="billing-address" wire:model="billingAddress" rows="4" class="field-control"></textarea>@error('billingAddress')<p class="mt-1.5 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endunless</section>
            <section class="surface p-6 sm:p-8"><div class="flex items-center gap-3"><span class="flex size-8 items-center justify-center rounded-full bg-orange-100 text-sm font-bold text-orange-700">3</span><div><h2 class="font-semibold text-slate-950">Payment & notes</h2><p class="text-sm text-slate-500">No card details required for this learning project.</p></div></div><div class="mt-6 rounded-xl border border-orange-200 bg-orange-50 p-4"><label class="flex cursor-pointer items-start gap-3"><input type="radio" wire:model="paymentMethod" value="Cash on Delivery" class="mt-0.5 size-4 border-slate-300 text-orange-600 focus:ring-orange-500"><span><span class="block text-sm font-semibold text-orange-950">Cash on Delivery</span><span class="mt-1 block text-xs leading-5 text-orange-800">Pay when your order arrives. This is the only payment method enabled in this practice store.</span></span></label></div><div class="mt-5"><label class="field-label" for="order-notes">Order notes <span class="font-normal text-slate-400">(optional)</span></label><textarea id="order-notes" wire:model="notes" rows="3" class="field-control" placeholder="Anything we should know?"></textarea>@error('notes')<p class="mt-1.5 text-sm text-red-600">{{ $message }}</p>@enderror</div></section>
        </div>
        <aside class="surface p-6 lg:sticky lg:top-28"><h2 class="text-lg font-semibold text-slate-950">Your order</h2><div class="mt-5 space-y-4">@foreach($items as $item)<div class="flex items-start gap-3"><div class="size-12 shrink-0 overflow-hidden rounded-lg bg-orange-50">@if($item['image'])<img src="{{ $item['image'] }}" alt="" class="h-full w-full object-cover">@else<x-product-placeholder :product="$item['product']" size="small" />@endif</div><div class="min-w-0 flex-1"><p class="truncate text-sm font-medium text-slate-900">{{ $item['name'] }}</p><p class="text-xs text-slate-500">Qty {{ $item['quantity'] }}</p></div><span class="text-sm font-semibold text-slate-900">${{ number_format($item['line_total'], 2) }}</span></div>@endforeach</div><div class="mt-6 space-y-3 border-t border-slate-200 pt-5 text-sm"><div class="flex justify-between text-slate-600"><span>Subtotal</span><span>${{ number_format($subtotal, 2) }}</span></div><div class="flex justify-between text-slate-600"><span>Delivery</span><span class="text-emerald-600">Free</span></div><div class="flex justify-between pt-2 text-lg font-bold text-slate-950"><span>Total</span><span>${{ number_format($subtotal, 2) }}</span></div></div><button type="submit" wire:loading.attr="disabled" class="btn btn-primary mt-6 w-full"><span wire:loading.remove>Place order</span><span wire:loading>Placing order…</span><x-icon name="check" size="17" wire:loading.remove /></button><p class="mt-3 text-center text-xs leading-5 text-slate-500">By placing your order, you agree to our simple demo-store terms.</p></aside>
    </form>
</div>
